// Building facts and listing-specific facts are kept separate.
window.CONDOS = [
  {id:1,name:'Asoke Place',building:{year:1996,station:'MRT Sukhumvit',distance:370,pool:'yes',sauna:'yes',cowork:'unknown',bath:'unknown',other:{th:'ห้องสมุดและห้องสำนักงาน',ja:'図書室・オフィスルーム'},lat:13.74169,lng:100.56239,coordinateSource:'https://mapcarta.com/W329745983',url:'https://propertyscout.co.th/en/bangkok/condo/asoke-place/',extra:['https://www.thailand-property.com/condo/1087/asoke-place']},unit:{area:75,floor:12,rent:25000,url:'https://propertyscout.co.th/en/2-br-condo-asoke-place-near-mrt-sukhumvit-2165264/'},gallery:'modal'},
  {id:2,name:'The Privacy Taopoon Interchange',building:{year:2020,yearConflict:'2021',station:'MRT Tao Poon',distance:630,pool:'yes',sauna:'yes',cowork:'yes',bath:'yes',other:{th:'ออนเซ็นบนดาดฟ้า ห้องสตีม ห้องประชุมและเลานจ์; ยังไม่ยืนยันอุณหภูมิและการเปิดใช้งาน',ja:'屋上onsen、スチーム、会議室、ラウンジ。温水・現時点の稼働は未確認'},lat:13.811687,lng:100.531575,coordinateSource:'https://www.homenayoo.com/the-privacy-taopoon-interchange/',url:'https://propertyscout.co.th/en/bangkok/condo/privacy-taopoon-interchange/',extra:['https://www.tr-realestate.co/projects/the-privacy-taopoon-interchange']},unit:{area:51.23,floor:12,rent:25000,url:'https://propertyscout.co.th/en/2-br-condo-the-privacy-taopoon-interchange-near-mrt-tao-poon-2698428/'},gallery:'modal'},
  {id:3,name:'The Waterford Diamond Tower Sukhumvit',building:{year:1999,station:'BTS Phrom Phong',distance:570,pool:'yes',sauna:'yes',cowork:'unknown',bath:'unknown',other:{th:'ลู่วิ่ง สนามเด็กเล่น ร้านค้า',ja:'ジョギングトラック、遊び場、館内店舗'},lat:13.7265,lng:100.57309,coordinateSource:'https://mapcarta.com/W76510915',url:'https://propertyscout.co.th/en/bangkok/condo/waterford-diamond-tower-sukhumvit/',extra:[]},unit:{area:60.3,floor:16,rent:35000,url:'https://propertyscout.co.th/en/2-br-condo-the-waterford-diamond-tower-sukhumvit-near-bts-phrom-phong-1413007/'},gallery:'modal'},
  {id:4,name:'Ideo Sukhumvit 93',building:{year:2018,station:'BTS Bang Chak',distance:180,pool:'yes',sauna:'yes',cowork:'yes',bath:'unknown',other:{th:'จากุซซีและห้องสตีม; ไม่พบการยืนยันออนเซ็น',ja:'ジャグジー・スチームバス。onsenは未確認'},lat:13.698331,lng:100.604758,coordinateSource:'https://www.homenayoo.com/ideo-sukhumvit-93/',url:'https://propertyscout.co.th/en/bangkok/condo/ideo-sukhumvit-93/',extra:[]},unit:{area:60,floor:null,rent:35000,url:'https://propertyscout.co.th/en/2-br-condo-ideo-sukhumvit-93-near-bts-bang-chak-2164082/'},gallery:'modal'},
  {id:5,name:'15 Sukhumvit Residences',building:{year:2013,station:'BTS Nana',distance:380,pool:'yes',sauna:'yes',cowork:'yes',bath:'unknown',other:{th:'คลับเฮาส์และสกายเลานจ์',ja:'クラブハウス、スカイラウンジ'},lat:13.74206,lng:100.55815,coordinateSource:'https://mapcarta.com/W340670160',url:'https://propertyscout.co.th/en/bangkok/condo/15-sukhumvit-residences/',extra:[]},unit:{area:62,floor:21,rent:35000,url:'https://propertyscout.co.th/en/2-br-condo-15-sukhumvit-residences-near-bts-nana-601795/'},gallery:'modal'},
  {id:6,name:'My Resort Bangkok Condominium',building:{year:2009,station:'MRT Phetchaburi',distance:330,pool:'yes',sauna:'yes',cowork:'unknown',bath:'unknown',other:{th:'ห้องสตีม',ja:'スチームルーム'},lat:13.748306,lng:100.566494,coordinateSource:'https://www.condonayoo.com/my-resort-bangkok/',url:'https://propertyscout.co.th/en/bangkok/condo/my-resort-bangkok-condominium/',extra:[]},unit:{area:70,floor:35,rent:30000,url:'https://propertyscout.co.th/en/2-br-condo-my-resort-bangkok-condominium-near-mrt-phetchaburi-961760/'},gallery:'modal'},
  {id:7,name:'Park Origin Thonglor',building:{year:2022,station:'BTS Thong Lo',distance:1080,pool:'yes',sauna:'yes',cowork:'yes',bath:'yes',other:{th:'ออนเซ็น จากุซซีและห้องสตีม; สิทธิ์ใช้งานแต่ละอาคารยังไม่ยืนยัน',ja:'共用onsen、ジャグジー、スチーム。指定部屋の棟別利用権は未確認'},lat:13.73160755,lng:100.58464684,coordinateSource:'https://thinkofliving.com/project/%E0%B8%84%E0%B8%AD%E0%B8%99%E0%B9%82%E0%B8%94/6554/',url:'https://propertyscout.co.th/en/bangkok/condo/park-origin-thonglor/',extra:['https://www.fazwaz.com/projects/thailand/bangkok/watthana/khlong-tan-nuea/park-origin-thonglor']},unit:{area:42,floor:17,rent:25000,url:'https://propertyscout.co.th/en/2-br-condo-park-origin-thonglor-near-bts-thong-lor-3244600/'},gallery:'unavailable'},
  {id:8,name:'The Waterford Park Sukhumvit 53 (Thong Lor 5)',building:{year:1992,station:'BTS Thong Lo',distance:730,pool:'yes',sauna:'yes',cowork:'unknown',bath:'unknown',other:{th:'สนามเด็กเล่นและร้านค้า',ja:'遊び場、館内店舗'},lat:13.730972,lng:100.57829,coordinateSource:'https://www.homenayoo.com/the-waterford-park-sukhumvit-53/',url:'https://propertyscout.co.th/en/bangkok/condo/waterford-park-sukhumvit-53-thong-lor-5/',extra:[]},unit:{area:90,floor:7,rent:26000,url:'https://propertyscout.co.th/en/2-br-condo-the-waterford-park-sukhumvit-53-thong-lor-5-near-bts-thong-lor-515669/'},gallery:'modal'},
  {id:9,name:'Life @ Sukhumvit 65',building:{year:2009,yearConflict:'late 2008',station:'BTS Phra Khanong',distance:320,pool:'yes',sauna:'yes-unverified',saunaEvidence:'listed-operation-unverified',cowork:'unknown',bath:'unknown',other:{th:'สวนและสนามเด็กเล่น; มีรายการซาวน่า แต่ยังไม่ยืนยันว่าเปิดใช้งานอยู่',ja:'庭・遊び場。サウナ設備の記載あり。現在の稼働状況は未確認'},lat:13.716932,lng:100.589094,coordinateSource:'https://www.bangkokre.com/projects/644',coordinateCaveat:true,url:'https://propertyscout.co.th/en/bangkok/condo/life-sukhumvit-65/',extra:['https://www.fazwaz.com/projects/thailand/bangkok/watthana/phra-khanong-nuea/life-at-sukhumvit-65','https://www.hipflat.com/projects/life-at-sukhumvit-65-kfuzgz']},unit:{area:63,floor:11,rent:31000,url:'https://propertyscout.co.th/en/2-br-condo-life-sukhumvit-65-near-bts-phra-khanong-2099598/'},gallery:'modal'},
  {id:10,name:'Ideo Verve Ratchaprarop',building:{year:2012,station:'ARL Ratchaprarop',distance:80,pool:'yes',sauna:'reported',saunaEvidence:'multiple-listings-onsite-check',cowork:'unknown',bath:'unknown',other:{th:'ฟิตเนส; หลายแหล่งระบุว่ามีซาวน่า ควรตรวจสอบที่โครงการว่ายังเปิดใช้งานหรือไม่',ja:'フィットネス。複数資料にサウナの記載あり。現在の利用可否は管理事務所に要確認'},lat:13.754687,lng:100.542654,coordinateSource:'https://www.homenayoo.com/ideo-verve-ratchaprarop/',url:'https://propertyscout.co.th/en/bangkok/condo/ideo-verve-ratchaprarop/',extra:['https://eng.scancondo.com/rent-condo/Ideo-Verve-Ratchaprarop','https://www.ennxo.com/condo/for-rent/project/ideo-verve-ratchaprarop','https://www.livinginsider.com/en/detail/condo-for-rent-condo-ideo-verve-ratchaprarop-2bedroom-3240614']},unit:{area:72,floor:14,rent:26600,url:'https://propertyscout.co.th/en/2-br-condo-ideo-verve-ratchaprarop-near-arl-ratchaprarop-1995914/'},gallery:'modal'}
];
