// Building facts and listing-specific facts are kept separate.
window.CONDOS = [
  {id:1,name:'Asoke Place',building:{year:1996,station:'MRT Sukhumvit',distance:370,pool:'yes',sauna:'yes',cowork:'unknown',bath:'unknown',other:{th:'ห้องสมุดและห้องสำนักงาน',ja:'図書室・オフィスルーム'},lat:13.74169,lng:100.56239,coordinateSource:'https://mapcarta.com/W329745983',url:'https://propertyscout.co.th/en/bangkok/condo/asoke-place/',extra:['https://www.thailand-property.com/condo/1087/asoke-place']},unit:{area:75,floor:12,rent:25000,url:'https://propertyscout.co.th/en/2-br-condo-asoke-place-near-mrt-sukhumvit-2165264/'},gallery:'modal'},
  {id:2,name:'The Privacy Taopoon Interchange',building:{year:2020,yearConflict:'2021',station:'MRT Tao Poon',distance:630,pool:'yes',sauna:'yes',cowork:'yes',bath:'unknown',onsen:{listed:'unknown',residentAccess:'unknown',operating:'unknown',note:{th:'เว็บนายหน้าบางแห่งระบุว่ามีออนเซ็น แต่เอกสารผู้พัฒนาและรีวิวหลังสร้างเสร็จยังไม่ยืนยัน',ja:'仲介サイトに記載あり。開発元の設備案内と完成後レビューでは裏づけ未確認'}},other:{th:'ห้องสตีม ห้องประชุมและเลานจ์; ห้องสตีมไม่ใช่หลักฐานของออนเซ็น',ja:'スチーム、会議室、ラウンジ。スチームをONSENの証拠としない'},lat:13.811687,lng:100.531575,coordinateSource:'https://www.homenayoo.com/the-privacy-taopoon-interchange/',url:'https://propertyscout.co.th/en/bangkok/condo/privacy-taopoon-interchange/',extra:['https://www.pruksa.com/theprivacy/taopoon-interchange','https://www.condonayoo.com/the-privacy-taopoon-interchange/']},unit:{area:51.23,floor:12,rent:25000,url:'https://propertyscout.co.th/en/2-br-condo-the-privacy-taopoon-interchange-near-mrt-tao-poon-2698428/'},gallery:'modal'},
  {id:3,name:'The Waterford Diamond Tower Sukhumvit',building:{year:1999,station:'BTS Phrom Phong',distance:570,pool:'yes',sauna:'yes',cowork:'unknown',bath:'unknown',other:{th:'ลู่วิ่ง สนามเด็กเล่น ร้านค้า',ja:'ジョギングトラック、遊び場、館内店舗'},lat:13.7265,lng:100.57309,coordinateSource:'https://mapcarta.com/W76510915',url:'https://propertyscout.co.th/en/bangkok/condo/waterford-diamond-tower-sukhumvit/',extra:[]},unit:{area:69,floor:44,rent:30000,availableFrom:'2027-09',url:'https://propertyscout.co.th/en/2-br-condo-the-waterford-diamond-tower-sukhumvit-near-bts-phrom-phong-1518702/'},gallery:'modal'},
  {id:4,name:'Ideo Sukhumvit 93',building:{year:2018,station:'BTS Bang Chak',distance:180,pool:'yes',sauna:'yes',cowork:'yes',bath:'unknown',other:{th:'จากุซซีและห้องสตีม; ไม่พบการยืนยันออนเซ็น',ja:'ジャグジー・スチームバス。onsenは未確認'},lat:13.698331,lng:100.604758,coordinateSource:'https://www.homenayoo.com/ideo-sukhumvit-93/',url:'https://propertyscout.co.th/en/bangkok/condo/ideo-sukhumvit-93/',extra:[]},unit:{area:53,floor:21,rent:30000,url:'https://propertyscout.co.th/en/2-br-condo-ideo-sukhumvit-93-near-bts-bang-chak-3286651/'},gallery:'modal'},
  {id:5,name:'15 Sukhumvit Residences',building:{year:2013,station:'BTS Nana',distance:380,pool:'yes',sauna:'yes',cowork:'yes',bath:'unknown',other:{th:'คลับเฮาส์และสกายเลานจ์',ja:'クラブハウス、スカイラウンジ'},lat:13.74206,lng:100.55815,coordinateSource:'https://mapcarta.com/W340670160',url:'https://propertyscout.co.th/en/bangkok/condo/15-sukhumvit-residences/',extra:[]},unit:{area:68,floor:19,rent:30000,url:'https://propertyscout.co.th/en/2-br-condo-15-sukhumvit-residences-near-bts-nana-3235123/'},gallery:'modal'},
  {id:6,name:'My Resort Bangkok Condominium',building:{year:2009,station:'MRT Phetchaburi',distance:330,pool:'yes',sauna:'yes',cowork:'unknown',bath:'unknown',other:{th:'ห้องสตีม',ja:'スチームルーム'},lat:13.748306,lng:100.566494,coordinateSource:'https://www.condonayoo.com/my-resort-bangkok/',url:'https://propertyscout.co.th/en/bangkok/condo/my-resort-bangkok-condominium/',extra:[]},unit:{area:70,floor:35,rent:30000,url:'https://propertyscout.co.th/en/2-br-condo-my-resort-bangkok-condominium-near-mrt-phetchaburi-961760/'},gallery:'modal'},
  {id:7,name:'Park Origin Thonglor',building:{year:2022,station:'BTS Thong Lo',distance:1080,pool:'yes',sauna:'yes',cowork:'yes',bath:'yes',onsen:{listed:'yes',residentAccess:'unknown',operating:'unknown',note:{th:'ข้อบังคับอาคารระบุออนเซ็นในห้องอาบน้ำแยกชายหญิง; อาคารของห้องนี้ สิทธิ์ใช้บริการ เวลา อุณหภูมิ และค่าบริการยังไม่ยืนยัน',ja:'管理規約に男女別浴室内のONSENを記載。指定部屋の棟・利用権、時間、湯温、料金、現行稼働は未確認'}},other:{th:'จากุซซีและห้องสตีม; สิทธิ์ใช้งานแต่ละอาคารยังไม่ยืนยัน',ja:'ジャグジー・スチーム。棟別の利用権は未確認'},lat:13.73160755,lng:100.58464684,coordinateSource:'https://thinkofliving.com/project/%E0%B8%84%E0%B8%AD%E0%B8%99%E0%B9%82%E0%B8%94/6554/',url:'https://propertyscout.co.th/en/bangkok/condo/park-origin-thonglor/',extra:['https://origin.co.th/wp-content/uploads/2023/03/%E0%B8%82%E0%B9%89%E0%B8%AD%E0%B8%9A%E0%B8%B1%E0%B8%87%E0%B8%84%E0%B8%B1%E0%B8%9A%E0%B8%99%E0%B8%B4%E0%B8%95%E0%B8%B4%E0%B8%9A%E0%B8%B8%E0%B8%84%E0%B8%84%E0%B8%A5%E0%B8%AF-Park-Origin-Thonglor.pdf']},unit:{area:42,floor:17,rent:25000,rentVerification:'recheck',url:'https://propertyscout.co.th/en/2-br-condo-park-origin-thonglor-near-bts-thong-lor-3244600/'},gallery:'unavailable'},
  {id:8,name:'The Waterford Park Sukhumvit 53 (Thong Lor 5)',building:{year:1992,station:'BTS Thong Lo',distance:730,pool:'yes',sauna:'yes',cowork:'unknown',bath:'unknown',other:{th:'สนามเด็กเล่นและร้านค้า',ja:'遊び場、館内店舗'},lat:13.730972,lng:100.57829,coordinateSource:'https://www.homenayoo.com/the-waterford-park-sukhumvit-53/',url:'https://propertyscout.co.th/en/bangkok/condo/waterford-park-sukhumvit-53-thong-lor-5/',extra:[]},unit:{area:90,floor:7,rent:26000,url:'https://propertyscout.co.th/en/2-br-condo-the-waterford-park-sukhumvit-53-thong-lor-5-near-bts-thong-lor-515669/'},gallery:'modal'},
  {id:9,name:'Life @ Sukhumvit 65',building:{year:2009,yearConflict:'late 2008',station:'BTS Phra Khanong',distance:320,pool:'yes',sauna:'yes-unverified',saunaEvidence:'listed-operation-unverified',cowork:'unknown',bath:'unknown',other:{th:'สวนและสนามเด็กเล่น; มีรายการซาวน่า แต่ยังไม่ยืนยันว่าเปิดใช้งานอยู่',ja:'庭・遊び場。サウナ設備の記載あり。現在の稼働状況は未確認'},lat:13.716932,lng:100.589094,coordinateSource:'https://www.bangkokre.com/projects/644',coordinateCaveat:true,url:'https://propertyscout.co.th/en/bangkok/condo/life-sukhumvit-65/',extra:['https://www.fazwaz.com/projects/thailand/bangkok/watthana/phra-khanong-nuea/life-at-sukhumvit-65','https://www.hipflat.com/projects/life-at-sukhumvit-65-kfuzgz']},unit:{area:56,floor:11,rent:28000,availableFrom:'2026-12',url:'https://propertyscout.co.th/en/2-br-condo-life-sukhumvit-65-near-bts-phra-khanong-1990148/'},gallery:'modal'},
  {id:10,name:'Ideo Verve Ratchaprarop',building:{year:2012,station:'ARL Ratchaprarop',distance:80,pool:'yes',sauna:'reported',saunaEvidence:'multiple-listings-onsite-check',cowork:'unknown',bath:'unknown',other:{th:'ฟิตเนส; หลายแหล่งระบุว่ามีซาวน่า ควรตรวจสอบที่โครงการว่ายังเปิดใช้งานหรือไม่',ja:'フィットネス。複数資料にサウナの記載あり。現在の利用可否は管理事務所に要確認'},lat:13.754687,lng:100.542654,coordinateSource:'https://www.homenayoo.com/ideo-verve-ratchaprarop/',url:'https://propertyscout.co.th/en/bangkok/condo/ideo-verve-ratchaprarop/',extra:['https://eng.scancondo.com/rent-condo/Ideo-Verve-Ratchaprarop','https://www.ennxo.com/condo/for-rent/project/ideo-verve-ratchaprarop','https://www.livinginsider.com/en/detail/condo-for-rent-condo-ideo-verve-ratchaprarop-2bedroom-3240614']},unit:{area:72,floor:14,rent:26600,url:'https://propertyscout.co.th/en/2-br-condo-ideo-verve-ratchaprarop-near-arl-ratchaprarop-1995914/'},gallery:'modal'},
  {id:11,name:'The Link Sukhumvit 50',building:{year:2012,station:'BTS On Nut',distance:290,pool:'yes',sauna:'unknown',cowork:'unknown',bath:'unknown',other:{th:'สวนและที่จอดรถ; ยังไม่ยืนยันซาวน่า โคเวิร์กกิ้ง หรือออนเซ็น',ja:'庭・駐車場。サウナ、コワーク、共用浴場は未確認'},lat:13.706489,lng:100.598286,coordinateSource:'https://www.condonayoo.com/?p=10865',coordinateCaveat:true,url:'https://propertyscout.co.th/en/bangkok/condo/link-sukhumvit-50/',extra:[]},unit:{area:71,floor:7,rent:25000,availableFrom:'2027-04',url:'https://propertyscout.co.th/en/2-br-condo-the-link-sukhumvit-50-near-bts-on-nut-1001877/'},gallery:'modal'},
  {id:12,name:'Grand Park View Asoke',building:{year:2004,station:'MRT Sukhumvit',distance:550,pool:'yes',sauna:'yes-unverified',cowork:'unknown',bath:'unknown',other:{th:'ฟิตเนส สวน และสนามเด็กเล่น; มีรายการซาวน่า แต่ยังไม่ยืนยันการเปิดใช้งาน',ja:'ジム・庭・遊び場。サウナの記載あり、現在の稼働は未確認'},lat:13.743436,lng:100.561635,coordinateSource:'https://www.bangkokre.com/projects/18',url:'https://propertyscout.co.th/en/bangkok/condo/grand-park-view-asoke/',extra:['https://www.fazwaz.com/projects/thailand/bangkok/watthana/khlong-toei-nuea/grand-park-view-asoke']},unit:{area:60,floor:23,rent:27000,url:'https://propertyscout.co.th/en/2-br-condo-grand-park-view-asoke-near-mrt-sukhumvit-2977882/'},gallery:'modal'},
  {id:13,name:'Tidy Deluxe Sukhumvit 34',building:{year:2014,station:'BTS Thong Lor',distance:400,pool:'yes',sauna:'yes',cowork:'yes',bath:'unknown',other:{th:'ห้องสตีม ห้องสมุด และรถรับส่ง; ห้องสตีมไม่ใช่ออนเซ็น',ja:'スチームルーム・図書室・シャトル。スチームを温泉とは扱わない'},lat:13.72519,lng:100.57472,coordinateSource:'https://mapcarta.com/W340092402',url:'https://propertyscout.co.th/en/bangkok/condo/tidy-deluxe-sukhumvit-34/',extra:[]},unit:{area:45.1,floor:5,rent:32000,url:'https://propertyscout.co.th/en/2-br-condo-tidy-deluxe-sukhumvit-34-near-bts-thong-lor-2281327/'},gallery:'modal'},
  {id:14,name:'Ideo Mobi Sukhumvit 66',building:{year:2017,station:'BTS Udom Suk',distance:160,pool:'yes',sauna:'yes',cowork:'unknown',bath:'unknown',other:{th:'ห้องสตีม ฟิตเนส สวน และเลานจ์; เลานจ์ไม่ใช่โคเวิร์กกิ้งที่ยืนยันแล้ว',ja:'スチーム・ジム・庭・ラウンジ。ラウンジを専用コワークとは断定しない'},lat:13.68177,lng:100.60963,coordinateSource:'https://mapcarta.com/W827834612',url:'https://propertyscout.co.th/en/bangkok/condo/ideo-mobi-sukhumvit-66/',extra:[]},unit:{area:54,floor:19,rent:28000,availableFrom:'2027-02',url:'https://propertyscout.co.th/en/2-br-condo-ideo-mobi-sukhumvit-66-near-bts-udom-suk-649103/'},gallery:'modal'},
  {id:15,name:'T.C. Green Rama 9',building:{year:2015,yearConflict:'2013',station:'MRT Phra Ram 9',distance:1150,pool:'yes',sauna:'reported',cowork:'unknown',bath:'unknown',other:{th:'มีรายการห้องสมุดและห้องสำนักงาน; โครงการหลายอาคาร ควรยืนยันสิทธิ์ใช้งานของห้องชั้น 29',ja:'図書室・オフィスルームの記載あり。複数棟のため29階の部屋の共用設備利用権は要確認'},lat:13.755117,lng:100.575119,coordinateSource:'https://www.condonayoo.com/tc-green-rama-9/',url:'https://propertyscout.co.th/en/bangkok/condo/tc-green-rama-9/',extra:['https://www.fazwaz.com/projects/thailand/bangkok/huai-khwang/huai-khwang/tc-green-rama-9','https://www.hipflat.com/projects/tc-green-woffho']},unit:{area:59.36,floor:29,rent:28000,url:'https://propertyscout.co.th/en/2-br-condo-tc-green-rama-9-near-mrt-phra-ram-9-1363893/'},gallery:'modal'},
  {id:16,name:'Knightsbridge Space Rama 9',building:{year:2021,station:'MRT Phra Ram 9',distance:450,pool:'yes',sauna:'unknown',cowork:'yes',bath:'yes',onsen:{listed:'yes',residentAccess:'unknown',operating:'unknown',note:{th:'มี Sky Sunrise Onsen แยกชายหญิง; รีวิวระบุ 33°C ณ วันที่สำรวจ ไม่ใช่อุณหภูมิปัจจุบัน; เวลาและค่าบริการยังไม่ยืนยัน',ja:'男女別Sky Sunrise Onsenの記載あり。33℃は取材当時の値で現在値ではない。利用権・時間・料金・稼働は未確認'}},other:{th:'มีห้องสตีม (ไม่ใช่การยืนยันซาวน่าแห้ง), Craft Café & Working Space และ Business Lounge',ja:'スチームルーム（ドライサウナは未確認）、Craft Café & Working Space、Business Lounge'},lat:13.756056,lng:100.562361,coordinateSource:'https://www.condonayoo.com/knightsbridge-space-rama-9/',coordinateCaveat:true,url:'https://www.homenayoo.com/knightsbridge-space-rama-9/',extra:[]},unit:{area:49,floor:9,rent:30000,rentVerification:'recheck',url:'https://propertyhub.in.th/en/listings/for-rent-condo-knightsbridge-space-rama-9-building-1-floor-9-duplex-2-bed-room-room-size-49-sqm--b29d0915---6344824'},gallery:'unavailable'},
  {id:17,name:'Vtara Sukhumvit 36',building:{year:2019,station:'BTS Thong Lo',distance:850,pool:'yes',sauna:'yes',cowork:'unknown',bath:'yes',onsen:{listed:'yes',residentAccess:'unknown',operating:'unknown',note:{th:'มีห้องออนเซ็นแยกชายหญิง; กฎระบุ 06:00–22:00 แต่การเปิดใช้งานจริงยังไม่ยืนยัน รีวิวเก่าระบุว่ามีค่าบริการต่อครั้ง (อัตราปัจจุบันไม่ทราบ)',ja:'男女別ONSEN室の記載あり。規則上06:00～22:00だが現行運用は未確認。過去のレビューに都度料金の記載あり（金額・現行料金は不明）'}},other:{th:'ห้องประชุมและห้องสมุด; ยังไม่ยืนยันว่าเป็นโคเวิร์กกิ้งเฉพาะทาง; มีรถรับส่ง BTS (ตารางและค่าโดยสารยังไม่ยืนยัน)',ja:'共用会議室・図書室あり。専用コワークかは未確認。BTSシャトルの掲載あり（現行ダイヤ・料金は未確認）'},lat:13.71755,lng:100.576275,coordinateSource:'https://www.baanfinder.com/en/property/%E0%B8%82%E0%B8%B2%E0%B8%A2%E0%B9%80%E0%B8%8A%E0%B9%88%E0%B8%B2%E0%B8%84%E0%B8%AD%E0%B8%99%E0%B9%82%E0%B8%94%E0%B8%A1%E0%B8%B4%E0%B9%80%E0%B8%99%E0%B8%B5%E0%B8%A2%E0%B8%A1-%E0%B8%A7%E0%B8%B5%E0%B8%98%E0%B8%B2%E0%B8%A3%E0%B8%B2-%E0%B8%AA%E0%B8%B8%E0%B8%82%E0%B8%B8%E0%B8%A1%E0%B8%A7%E0%B8%B4%E0%B8%9736-%E0%B8%84%E0%B8%A5%E0%B8%AD%E0%B8%87%E0%B9%80%E0%B8%95%E0%B8%A2-%E0%B8%81%E0%B8%A3%E0%B8%B8%E0%B8%87%E0%B9%80%E0%B8%97%E0%B8%9E%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B8%A3--41394914',coordinateCaveat:true,url:'https://www.fazwaz.com/projects/thailand/bangkok/khlong-toei/khlong-tan/vtara-sukhumvit-36',extra:['https://www.vtara36.org/th/','https://www.condonayoo.com/vtara-36/']},unit:{area:50.54,floor:null,rent:29000,building:'A',bathtub:true,url:'https://propertyhub.in.th/en/listings/nice-bright-2-beds-2-baths-with-bathtub-shuttle-bus-to-bts-thong-lo-at-vtara-sukhumvit-36-condo-for-rent---4172552'},gallery:'unavailable'}
];

// The catalog retains every candidate; only independently checked two-bedroom rentals enter the public view.
window.SUPERSEDED_UNITS = [
  { condoId: 3, rent: 35000, url: 'https://propertyscout.co.th/en/2-br-condo-the-waterford-diamond-tower-sukhumvit-near-bts-phrom-phong-1413007/' },
  { condoId: 4, rent: 35000, url: 'https://propertyscout.co.th/en/2-br-condo-ideo-sukhumvit-93-near-bts-bang-chak-2164082/' },
  { condoId: 5, rent: 35000, url: 'https://propertyscout.co.th/en/2-br-condo-15-sukhumvit-residences-near-bts-nana-601795/' },
];
const verifiedUnitIds = new Set([1,3,4,5,6,7,8,9,10,11,12,15,16,17]);
for (const entry of window.CONDOS) {
  if (verifiedUnitIds.has(entry.id)) {
    entry.unit.bedrooms = 2;
    entry.unit.priceCheckedAt = '2026-10-02';
  }
}
// Independent listing records share building facts and the stable building vote ID.
const facebookNote = {
  th: 'ข้อมูลประกาศจากผู้ใช้; ยังตรวจสอบโพสต์และห้องซ้ำไม่ได้ โปรดยืนยันราคาและห้องว่างกับผู้ประกาศ',
  ja: 'ユーザー提供の募集情報。投稿・同一室照合は未確認。賃料・空室は募集者へ要確認',
};
for (const entry of window.CONDOS) entry.units = [{ ...entry.unit, listingId: `legacy-${entry.id}` }];
const vtara = window.CONDOS.find(entry => entry.id === 17);
vtara.units[0].note = { th: 'ประกาศเดิมตรวจสอบราคา 2026-10-02; ยังเทียบห้องกับโพสต์ใหม่ไม่ได้ โปรดยืนยันห้องว่าง', ja: '既存募集の価格確認日2026-10-02。新投稿との同一室照合・現在の空室は要確認' };
vtara.units.push(
  { listingId: 'fb-1ErKPqgSij', bedrooms: 2, bathrooms: null, area: 50, floor: null, rent: 23000, priceCheckedAt: '2026-10-05', note: facebookNote, url: 'https://www.facebook.com/share/p/1ErKPqgSij/?mibextid=wwXIfr' },
  { listingId: 'fb-1A9Yq99LHn', bedrooms: 2, bathrooms: 2, area: 50, floor: null, rent: 25000, leaseMonths: 12, priceCheckedAt: '2026-10-05', note: facebookNote, url: 'https://www.facebook.com/share/p/1A9Yq99LHn/' }
);
const mobi = window.CONDOS.find(entry => entry.id === 14);
mobi.building.yearConflict = '2018';
mobi.building.extra.push('https://www.hipflat.com/projects/ideo-mobi-sukhumvit-66-lbanvm');
mobi.units.push({ listingId: 'fb-1EWeLVosWT', bedrooms: 2, bathrooms: 1, area: 52.06, floor: 9, rent: 27000, bathtub: true, priceCheckedAt: '2026-10-05', note: facebookNote, url: 'https://www.facebook.com/share/p/1EWeLVosWT/' });
const riverUrl = 'https://www.fazwaz.com/projects/thailand/bangkok/bang-kho-laem/bang-kho-laem/river-heaven';
const riverUnit = { listingId: 'fb-1HZ7bJwzB9', bedrooms: 2, bathrooms: 1, area: 65, floor: 6, rent: 29500, leaseMonths: 12, bathtub: true, priceCheckedAt: '2026-10-05', note: facebookNote, url: 'https://www.facebook.com/share/p/1HZ7bJwzB9/' };
window.CONDOS.push({ id: 18, name: 'River Heaven', building: { year: 2003, station: 'BTS Saphan Taksin', distance: 4100, distanceMode: { th: 'ระยะทางโดยรถตามแหล่งข้อมูล ไม่ใช่ระยะเดิน', ja: '掲載資料の車移動距離。徒歩距離ではありません' }, pool: 'yes', sauna: 'yes', cowork: 'unknown', bath: 'unknown', other: { th: 'ฟิตเนส สวน เทนนิส บาสเกตบอล ร้านอาหาร; โพสต์ระบุโคเวิร์กกิ้ง/ห้องสมุด แต่ข้อมูลอาคารยังไม่ยืนยัน จำนวนสระยังไม่ยืนยัน', ja: 'ジム・庭・テニス・バスケットボール・館内飲食店。コワーク・図書室は募集投稿に記載、建物資料で裏づけ未確認。プール数は未確認' }, lat: 13.7011013, lng: 100.5014005, coordinateSource: 'https://propertyhub.in.th/en/projects/river-heaven', url: riverUrl, extra: ['https://www.hipflat.com/projects/river-heaven-wjgvwl'] }, unit: riverUnit, units: [riverUnit], gallery: 'unavailable' });
window.isPublicUnit = unit => unit.bedrooms === 2 && Number.isFinite(unit.rent) &&
  unit.rent > 0 && unit.rent <= 31000 && typeof unit.priceCheckedAt === 'string' &&
  Date.now() + 86400000 >= Date.parse(unit.priceCheckedAt) &&
  Date.now() - Date.parse(unit.priceCheckedAt) < 31 * 86400000;
window.PUBLIC_CONDOS = window.CONDOS.filter(entry => {
  const bySource = new Map();
  for (const unit of entry.units.filter(window.isPublicUnit)) {
    const url = new URL(unit.url);
    url.searchParams.delete('mibextid');
    url.hash = '';
    const key = url.href;
    const previous = bySource.get(key);
    if (!previous || unit.priceCheckedAt > previous.priceCheckedAt) bySource.set(key, unit);
  }
  entry.publicUnits = [...bySource.values()].sort((a, b) => a.rent - b.rent || a.listingId.localeCompare(b.listingId));
  return entry.publicUnits.length > 0;
});
window.REVIEW_CONDOS = window.CONDOS.filter(entry => !window.PUBLIC_CONDOS.includes(entry));

// Stable IDs remain unchanged for saved votes. Map numbers are geographic labels only.
const recommendations = [
  { id: 7, rank: 1, shuttle: 'free-advertised', source: 'https://www.instagram.com/reel/DKzaZBqOPQb/', note: { th: 'มีโฆษณาระบุรถรับส่งฟรีไป BTS ทองหล่อ; ตารางเดินรถและสิทธิ์ของผู้พักอาศัยปัจจุบันยังไม่ยืนยัน', ja: 'BTSトンロー行き無料送迎の案内あり。現行ダイヤ・居住者の利用条件は未確認' } },
  { id: 16, rank: 2, shuttle: 'unverified', source: 'https://propertyhub.in.th/en/condo-for-rent/project-knightsbridge-space-rama-9', note: { th: 'มีการกล่าวถึงรถรับส่ง แต่ยังยืนยันบริการและการใช้ฟรีไม่ได้', ja: '送迎への言及あり。ただしサービスの有無・無料かは確認できていません' } },
  { id: 17, rank: 3, shuttle: 'free-advertised', source: 'https://bkk-homes.com/properties/thong-lo/vtara-sukhumvit-36--txYQ72cXazHCAUN5Ruhh', note: { th: 'โฆษณาเช่าระบุรถรับส่งฟรีไป BTS ทองหล่อ; ตารางเดินรถและเงื่อนไขปัจจุบันยังไม่ยืนยัน', ja: 'BTSトンロー行き無料送迎との賃貸広告あり。現行ダイヤ・利用条件は未確認' } },
  { id: 4, rank: 4, shuttle: 'unverified', source: null, note: { th: 'ยังไม่มีหลักฐานยืนยันรถรับส่งฟรีของอาคารนี้; อย่าสับสนกับโครงการอื่นบนสุขุมวิท 93', ja: 'この建物の無料送迎は未確認。他のSukhumvit 93物件の広告と混同しないでください' } },
  { id: 3, rank: 5, shuttle: 'reported', source: 'https://www.superagent.co/en/blog/the-waterford-diamond-sukhumvit-30-classic-mid-sukhumvit-condo-reviewed', note: { th: 'รีวิวอาคารกล่าวถึงรถรับส่ง แต่ยังไม่ยืนยันว่าฟรีหรือยังให้บริการอยู่', ja: '建物レビューに送迎への言及あり。無料か・現行運行かは未確認' } },
  { id: 15, rank: 6, shuttle: 'free-advertised', source: 'https://goodyieldprop.com/property/rama-9-ratchada-huai-khwang-rca-suthisan/tc-green-rama-9-gy-mumja6ao', note: { th: 'โฆษณาเช่าระบุรถรับส่งฟรีไป MRT พระราม 9; ยังไม่ยืนยันการเดินรถปัจจุบัน', ja: 'MRT Rama 9行き無料送迎との賃貸広告あり。現行運行は未確認' } },
  { id: 5, rank: 7, shuttle: 'reported', source: 'https://condoreviewsthailand.com/buildings/15-sukhumvit-residences', note: { th: 'รีวิวกล่าวถึงรถตุ๊กตุ๊กรับส่ง แต่ยังไม่ยืนยันว่าฟรีหรือยังให้บริการอยู่', ja: 'トゥクトゥク送迎への言及あり。無料か・現行運行かは未確認' } },
  { id: 1, rank: 8, shuttle: 'unverified', source: null, note: { th: 'ยังไม่พบหลักฐานยืนยันรถรับส่งฟรี; ไม่ได้หมายความว่าไม่มีบริการ', ja: '無料送迎は確認できず。送迎なしと断定するものではありません' } },
  { id: 8, rank: 9, shuttle: 'reported', source: 'https://propertyhub.in.th/en/projects/the-waterford-park-sukhumvit-53', note: { th: 'มีข้อมูลกล่าวถึงรถรับส่ง แต่ยังไม่ยืนยันว่าฟรีหรือยังให้บริการอยู่', ja: '送迎の掲載あり。無料か・現行運行かは未確認' } },
  { id: 6, rank: 10, shuttle: 'unverified', source: null, note: { th: 'ยังไม่พบหลักฐานยืนยันรถรับส่งฟรี; ไม่ได้หมายความว่าไม่มีบริการ', ja: '無料送迎は確認できず。送迎なしと断定するものではありません' } },
  { id: 9, rank: 11, shuttle: 'unverified', source: null, note: { th: 'ยังไม่พบหลักฐานยืนยันรถรับส่งฟรี; ไม่ได้หมายความว่าไม่มีบริการ', ja: '無料送迎は確認できず。送迎なしと断定するものではありません' } },
  { id: 12, rank: 12, shuttle: 'unverified', source: null, note: { th: 'ยังไม่พบหลักฐานยืนยันรถรับส่งฟรี; ไม่ได้หมายความว่าไม่มีบริการ', ja: '無料送迎は確認できず。送迎なしと断定するものではありません' } },
  { id: 10, rank: 13, shuttle: 'unverified', source: null, note: { th: 'ยังไม่มีหลักฐานยืนยันรถรับส่งฟรีสำหรับอาคารนี้', ja: 'この建物の無料送迎は未確認です' } },
  { id: 11, rank: 14, shuttle: 'unverified', source: null, note: { th: 'ยังไม่พบหลักฐานยืนยันรถรับส่งฟรี; อย่าสับสนกับ Waterford Sukhumvit 50', ja: '無料送迎は確認できず。近隣のWaterford Sukhumvit 50と混同しないでください' } },
];
for (const entry of window.PUBLIC_CONDOS) {
  const recommendation = recommendations.find(item => item.id === entry.id) || { rank: null, shuttle: 'unverified', source: null, note: { th: 'ยังไม่ยืนยันรถรับส่งฟรี; อาคารนี้ยังไม่ได้จัดอันดับ', ja: '無料送迎は未確認。この建物は推奨順位未評価' } };
  Object.assign(entry, { recommendationRank: recommendation.rank, shuttle: recommendation });
}
window.PUBLIC_CONDOS.slice().sort((a, b) => b.building.lng - a.building.lng || a.id - b.id)
  .forEach((entry, index) => { entry.mapNumber = index + 1; });
window.PUBLIC_LISTINGS = window.PUBLIC_CONDOS.flatMap(entry => entry.publicUnits.map(unit => ({ ...entry, unit })));
